site_name: Scholarly Citation Finder
repo_url: https://github.com/citationfinder/scholarly_citation_finder
repo_name: GitHub
theme: readthedocs
site_description: Documentation for Scholarly Citation Finder
pages:
- ['index.md', 'Home']
- ['deployment.md', 'User manuel', 'Deployment']
- ['setup.md', 'User manuel', 'Setup']
- ['api.md', 'User manuel', 'API']
- ['integration.md', 'Extension', 'Integration']