site_name: Scholarly Citation Finder
repo_url: https://github.com/citationfinder/scholarly_citation_finder
repo_name: GitHub
theme: readthedocs
site_description: Documentation for Scholarly Citation Finder
include_search: true
pages:
- ['index.md', 'Home']
- ['deployment.md', 'Developer manuel', 'Deployment']
- ['setup.md', 'Developer manuel', 'Setup']
- ['tools.md', 'Developer manuel', 'Tools']
- ['api.md', 'User manuel', 'API']
- ['harvester.md', 'User manuel', 'Harvester']
- ['integration.md', 'User manuel', 'Integration']
- ['evaluation.md', 'User manuel', 'Evaluation']