#!/usr/bin/python
# -*- coding: utf-8 -*-
class IsiFieldofstudy():
    
    # Maps the MAG field of studies to the ISI field of studies
    mappingLevel0 = {
        'Engineering': 'Engineering',
        'History': 'Social Sciences, general',
        'Environmental science': 'Environment/Ecology',
        'Psychology': 'Psychiatry/Psychology',
        'Biology': 'Biology & Biochemistry',
        'Materials Science': 'Materials Science',
        'Geography': 'Geosciences',
        'Mathematics': 'Mathematics',
        'Political Science': 'Social Sciences, general',
        'Computer Science': 'Computer Science',
        'Business': 'Economics & Business',
        'Geology': 'Geosciences',
        'Chemistry': 'Chemistry',
        'Physics': 'Physics',
        'Sociology': 'Social Sciences, general',
        'Economics': 'Economics & Business'
    }
    
    mappingLevel1 = {
        'Quantum mechanics':'Physics',
        'Applied psychology':'Psychiatry/Psychology',
        #'Physical therapy':None,
        'Anthropology':'Social Sciences, general',
        'Mathematical analysis':'Mathematics',
        #'Marketing':None,
        #'Dentistry':None,
        'Finance':'Economics & Business',
        'Social science':'Social Sciences, general',
        'Astrophysics':'Physics',
        'Environmental chemistry':'Chemistry',
        'Demography':'Social Sciences, general',
        'Ceramic materials':'Materials Science',
        'Human computer interaction':'Computer Science',
        'Internet privacy':'Computer Science',
        'Seismology':'Geosciences',
        'Marine engineering':'Engineering',
        'Applied mathematics':'Mathematics',
        'Climatology':'Geosciences',
        'Biochemical engineering':'Engineering',
        #'Dermatology':None,
        #'Environmental ethics':None,
        'Operating system':'Computer Science',
        'Composite material':'Materials Science',
        'Management':'Economics & Business',
        #'Pulp and paper industry':None,
        'Agronomy':'Agricultural Sciences',
        #'Telecommunications':None,
        'Environmental planning':'Environment/Ecology',
        'Surgery':'Clinical Medicine',
        'Mathematical Economics':'Economics & Business',
        'Automotive engineering':'Engineering',
        'Transport engineering':'Engineering',
        'Chromatography':'Chemistry',
        'Economic policy':'Social Sciences, general',
        #'Aesthetics':None,
        'Emergency medicine':'Clinical Medicine',
        #'Cancer research':None,
        'Monetary economics':'Economics & Business',
        #'Alternative medicine':None,
        'Nuclear chemistry':'Chemistry',
        #'Engineering ethics':None,
        'Stereochemistry':'Chemistry',
        'Topology':'Mathematics',
        'Molecular biology':'Molecular Biology & Genetics',
        #'Traditional medicine':None,
        'Information retrieval':'Computer Science',
        'Manufacturing engineering':'Engineering',
        'Computer network':'Computer Science',
        'Archaeology':'Social Sciences, general',
        #'Religious Studies':None,
        #'Theology':None,
        'Nuclear magnetic resonance':'Physics',
        'Actuarial science':'Mathematics',
        'Astrobiology':'Space Science',
        'Electrical engineering':'Engineering',
        'Geodesy':'Engineering',
        'Accounting':'Economics & Business',
        'Calculus':'Mathematics',
        #'Gerontology':None,
        'Agricultural engineering':'Engineering',
        'Construction engineering':'Engineering',
        #'Audiology':None,
        'Physical Chemistry':'Chemistry',
        #'Performance art':None,
        #'Diabetes mellitus':None,
        'Crystallography':'Geosciences',
        'Remote sensing':'Geosciences',
        'Statistics':'Mathematics',
        'Engineering Management':'Engineering',
        'Inorganic chemistry':'Chemistry',
        'International Economics':'Economics & Business',
        'Hydrology':'Geosciences',
        'Arithmetic':'Mathematics',
        #'Urology':None,
        'Developmental psychology':'Psychiatry/Psychology',
        'Artificial intelligence':'Computer Science',
        'Astronomy':'Space Science',
        'Geochemistry':'Chemistry',
        'Agroforestry':'Agricultural Sciences',
        #'Physical medicine and rehabilitation':None,
        #'Pathology':None,
        #'Pediatrics':None,
        'Industrial engineering':'Engineering',
        'Physical geography':'Geosciences',
        'Operations research':'Mathematics',
        'Biochemistry':'Biology & Biochemistry',
        'Mechanics':'Physics',
        'Law and economics':'Economics & Business',
        'Reliability engineering':'Engineering',
        'Geometry':'Mathematics',
        'Pharmacology':'Pharmacology & Toxicology',
        'Software Engineering':'Computer Science',
        'Agricultural science':'Agricultural Sciences',
        #'Ophthalmology':None,
        'Distributed computing':'Computer Science',
        'Metallurgy':'Materials Science',
        'Mathematical physics':'Mathematics',
        'Development economics':'Economics & Business',
        #'Endocrinology':None,
        #'Nanotechnology':None,
        'Radiochemistry':'Chemistry',
        'Ancient history':'Social Sciences, general',
        'Algorithm':'Computer Science',
        'Combinatorial chemistry':'Chemistry',
        'Particle physics':'Physics',
        'Computer graphics (images)':'Computer Science',
        'Earth science':'Geosciences',
        'Ethnology':'Social Sciences, general',
        'Nuclear engineering':'Engineering',
        'Econometrics':'Economics & Business',
        'Parallel computing':'Computer Science',
        'Natural resource economics':'Economics & Business',
        #'Aeronautics':None,
        #'Cartography':None,
        'Structural engineering':'Engineering',
        'Social psychology':'Psychiatry/Psychology',
        'Forestry':'Environment/Ecology',
        'Psychotherapist':'Psychiatry/Psychology',
        'Clinical psychology':'Psychiatry/Psychology',
        'Photochemistry':'Chemistry',
        #'Epistemology':None,
        'Chemical physics':'Physics',
        'Zoology':'Plant & Animal Science',
        #'Biotechnology':None,
        'Industrial organization':'Economics & Business',
        'Forensic engineering':'Engineering',
        'Economic geography':'Economics & Business',
        'Polymer science':'Materials Science',
        'Embedded system':'Computer Science',
        #'Cognitive science':None,
        #'Nuclear medicine':None,
        'Toxicology':'Pharmacology & Toxicology',
        'Criminology':'Social Sciences, general',
        #'Biological engineering':None,
        #'Intensive Care Medicine':None,
        'Computer security':'Computer Science',
        'Bioinformatics':'Computer Science',
        'Statistical physics':'Physics',
        'Welfare economics':'Economics & Business',
        'Economic system':'Economics & Business',
        'Environmental Engineering':'Engineering',
        #'Oncology':None,
        'Organic chemistry':'Chemistry',
        'Law':'Social Sciences, general',
        #'Food science':None,
        'Public Relations':'Economics & Business',
        #'Optoelectronics':None,
        'Labour economics':'Economics & Business',
        'Civil Engineering':'Engineering',
        'Regional science':'Social Sciences, general',
        'Neuroscience':'Neuroscience & Behavior',
        'Horticulture':'Agricultural Sciences',
        'Natural language processing':'Computer Science',
        #'Fishery':None,
        'Linguistics':'Social Sciences, general',
        'Theoretical computer science':'Computer Science',
        #'Medical emergency':None,
        'Financial system':'Economics & Business',
        'Combinatorics':'Mathematics',
        'Classical economics':'Economics & Business',
        'Pattern recognition':'Computer Science',
        #'Orthodontics':None,
        #'Anesthesia':None,
        'Discrete mathematics':'Mathematics',
        'Environmental economics':'Economics & Business',
        'Atomic physics':'Physics',
        'Process management':'Economics & Business',
        'Engineering drawing':'Engineering',
        #'Computational biology':None,
        'Microbiology':'Microbiology',
        'Mathematical optimization':'Mathematics',
        #'Paleontology':None,
        'Meteorology':'Geosciences',
        'Biophysics':'Biology & Biochemistry',
        #'Humanities':None,
        'Cognitive psychology':'Psychiatry/Psychology',
        'Immunology':'Immunology',
        'Water resource management':'Environment/Ecology',
        #'Knowledge management':None,
        'Financial economics':'Economics & Business',
        #'Visual arts':None,
        #'Nursing':None,
        'Microeconomics':'Economics & Business',
        'Nuclear physics':'Physics',
        'Atmospheric sciences':'Geosciences',
        'Gender studies':'Social Sciences, general',
        'Geomorphology':'Geosciences',
        'Optics':'Physics',
        'Control engineering':'Engineering',
        #'Family medicine':None,
        'Computer hardware':'Computer Science',
        #'Optometry':None,
        'Machine learning':'Computer Science',
        #'Obstetrics':None,
        'Mathematics education':'Social Sciences, general',
        'Polymer chemistry':'Chemistry',
        'Waste management':'Environment/Ecology',
        'Computational science':'Computer Science',
        'Electronic engineering':'Engineering',
        'Physiology':'Biology & Biochemistry',
        'Economic growth':'Economics & Business',
        #'Control theory':None,
        'Molecular physics':'Physics',
        #'Simulation':None,
        'Thermodynamics':'Physics',
        'Pedagogy':'Social Sciences, general',
        'Anatomy':'Biology & Biochemistry',
        'Analytical chemistry':'Chemistry',
        'Soil science':'Geosciences',
        #'Risk analysis':None,
        #'Literature':None,
        'Aerospace Engineering':'Engineering',
        'Geotechnical engineering':'Engineering',
        'Mineralogy':'Geosciences',
        'Quantum electrodynamics':'Physics',
        'Petroleum Engineering':'Engineering',
        'Medical education':'Social Sciences, general',
        'Geophysics':'Geosciences',
        #'Process engineering':None,
        'Botany':'Plant & Animal Science',
        'Petrology':'Geosciences',
        'Mechanical Engineering':'Engineering',
        'Speech recognition':'Computer Science',
        'Real-time computing':'Computer Science',
        'Public administration':'Social Sciences, general',
        'Socioeconomics':'Social Sciences, general',
        'Communication':'Social Sciences, general',
        'Programming language':'Computer Science',
        'Environmental protection':'Environment/Ecology',
        #'Management science':None,
        #'Gynecology':None,
        'Oceanography':'Geosciences',
        'Psychiatry':'Psychiatry/Psychology',
        'Medicinal chemistry':'Chemistry',
        #'Cardiology':None,
        'Systems engineering':'Engineering',
        'Veterinary medicine':'Plant & Animal Science',
        #'Advertising':None,
        'Macroeconomics':'Economics & Business',
        'Theoretical physics':'Physics',
        #'Engineering physics':None,
        #'Classics':None,
        #'Medical physics':None,
        'Market economy':'Economics & Business',
        #'Art history':None,
        'Classical mechanics':'Physics',
        'Environmental health':'Environment/Ecology',
        'Public economics':'Economics & Business',
        'Pure mathematics':'Mathematics',
        'Cell biology':'Molecular Biology & Genetics',
        'Data mining':'Computer Science',
        'Computational chemistry':'Chemistry',
        #'Acoustics':None,
        'Computational physics':'Physics',
        'Genealogy':'Social Sciences, general',
        'Computer Engineering':'Computer Science',
        'Algebra':'Mathematics',
        'Neoclassical economics':'Economics & Business',
        'International trade':'Economics & Business',
        'Business Administration':'Economics & Business',
        'Evolutionary biology':'Biology & Biochemistry',
        'Political Economy':'Economics & Business',
        'Psychoanalysis':'Psychiatry/Psychology',
        'Ecology':'Environment/Ecology',
        'Computer vision':'Computer Science',
        'Environmental resource management':'Environment/Ecology',
        'Animal science':'Plant & Animal Science',
        'Condensed matter physics':'Physics',
        'Media studies':'Social Sciences, general',
        'Commerce':'Economics & Business',
        'Database':'Computer Science',
        'Computer architecture':'Computer Science',
        'Library science':'Social Sciences, general',
        'Economic history':'Economics & Business',
        'Mining engineering':'Engineering',
        'Chemical Engineering':'Engineering',
        #'Radiology':None,
        #'Virology':None,
        'Keynesian economics':'Economics & Business',
        'General surgery':'Clinical Medicine',
        #'Internal medicine':None,
        'Economy':'Economics & Business',
        'Positive economics':'Economics & Business',
        'World Wide Web':'Computer Science',
        'Architectural engineering':'Engineering',
        'Biological system':'Biology & Biochemistry',
        'Operations management':'Economics & Business',
        'Genetics':'Molecular Biology & Genetics',
        #'Gastroenterology':None
    }