#!/usr/bin/python
# -*- coding: utf-8 -*-
class IsiFieldofstudy():
    
    # Maps the MAG field of studies to the ISI field of studies
    mappingLevel0 = {
        'Engineering': 'Engineering',
        'History': 'Social Sciences, general',
        'Environmental science': 'Environment/Ecology',
        'Psychology': 'Psychiatry/Psychology',
        'Biology': 'Biology & Biochemistry',
        'Materials Science': 'Materials Science',
        'Geography': 'Geosciences',
        'Mathematics': 'Mathematics',
        'Political Science': 'Social Sciences, general',
        'Computer Science': 'Computer Science',
        'Business': 'Economics & Business',
        'Geology': 'Geosciences',
        'Chemistry': 'Chemistry',
        'Physics': 'Physics',
        'Sociology': 'Social Sciences, general',
        'Economics': 'Economics & Business'
    }
    
    mappingLevel1 = {
        'Quantum mechanics':'Physics',
        'Applied psychology':'Psychiatry/Psychology',
        #'Physical therapy':'null'
        'Anthropology':'Social Sciences, general',
        'Mathematical analysis':'Mathematics',
        #'Marketing':'null',
        #'Dentistry':'null',
        'Finance':'Economics & Business',
        'Social science':'Social Sciences, general',
        'Astrophysics':'Physics',
        'Environmental chemistry':'Chemistry',
        'Demography':'Social Sciences, general',
        'Ceramic materials':'Materials Science',
        'Human computer interaction':'Computer Science',
        'Internet privacy':'Computer Science',
        'Seismology':'Geosciences',
        'Marine engineering':'Engineering',
        'Applied mathematics':'Mathematics',
        'Climatology':'Geosciences',
        'Biochemical engineering':'Engineering',
        #'Dermatology':'null',
        #'Environmental ethics':'null',
        'Operating system':'Computer Science',
        'Composite material':'Materials Science',
        'Management':'Economics & Business',
        'Pulp and paper industry':'null',
        'Agronomy':'Agricultural Sciences',
        'Telecommunications':'null',
        'Environmental planning':'Environment/Ecology',
        'Surgery':'Clinical Medicine',
        'Mathematical Economics':'Economics & Business',
        'Automotive engineering':'Engineering',
        'Transport engineering':'Engineering',
        'Chromatography':'Chemistry',
        'Economic policy':'Social Sciences, general',
        'Aesthetics':'null',
        'Emergency medicine':'Clinical Medicine',
        'Cancer research':'null',
        'Monetary economics':'Economics & Business',
        'Alternative medicine':'null',
        'Nuclear chemistry':'Chemistry',
        'Engineering ethics':'null',
        'Stereochemistry':'Chemistry',
        'Topology':'Mathematics',
        'Molecular biology':'Molecular Biology & Genetics',
        'Traditional medicine':'null',
        'Information retrieval':'Computer Science',
        'Manufacturing engineering':'Engineering',
        'Computer network':'Computer Science',
        'Archaeology':'Social Sciences, general',
        'Religious Studies':'null',
        'Theology':'null',
        'Nuclear magnetic resonance':'Physics',
        'Actuarial science':'Mathematics',
        'Astrobiology':'Space Science',
        'Electrical engineering':'Engineering',
        'Geodesy':'Engineering',
        'Accounting':'Economics & Business',
        'Calculus':'Mathematics',
        #'Gerontology':'null',
        'Agricultural engineering':'Engineering',
        'Construction engineering':'Engineering',
        #'Audiology':'null',
        'Physical Chemistry':'Chemistry',
        #'Performance art':'null',
        #'Diabetes mellitus':'null',
        'Crystallography':'Geosciences',
        'Remote sensing':'Geosciences',
        'Statistics':'Mathematics',
        'Engineering Management':'Engineering',
        'Inorganic chemistry':'Chemistry',
        'International Economics':'Economics & Business',
        'Hydrology':'Geosciences',
        'Arithmetic':'Mathematics',
        #'Urology':'null',
        'Developmental psychology':'Psychiatry/Psychology',
        'Artificial intelligence':'Computer Science',
        'Astronomy':'Space Science',
        'Geochemistry':'Chemistry',
        'Agroforestry':'Agricultural Sciences',
        #'Physical medicine and rehabilitation':'null',
        #'Pathology':'null',
        #'Pediatrics':'null',
        'Industrial engineering':'Engineering',
        'Physical geography':'Geosciences',
        'Operations research':'Mathematics',
        'Biochemistry':'Biology & Biochemistry',
        'Mechanics':'Physics',
        'Law and economics':'Economics & Business',
        'Reliability engineering':'Engineering',
        'Geometry':'Mathematics',
        'Pharmacology':'Pharmacology & Toxicology',
        'Software Engineering':'Computer Science',
        'Agricultural science':'Agricultural Sciences',
        #'Ophthalmology':'null',
        'Distributed computing':'Computer Science',
        'Metallurgy':'Materials Science',
        'Mathematical physics':'Mathematics',
        'Development economics':'Economics & Business',
        #'Endocrinology':'null',
        #'Nanotechnology':'null',
        'Radiochemistry':'Chemistry',
        'Ancient history':'Social Sciences, general',
        'Algorithm':'Computer Science',
        'Combinatorial chemistry':'Chemistry',
        'Particle physics':'Physics',
        'Computer graphics (images)':'Computer Science',
        'Earth science':'Geosciences',
        'Ethnology':'Social Sciences, general',
        'Nuclear engineering':'Engineering',
        'Econometrics':'Economics & Business',
        'Parallel computing':'Computer Science',
        'Natural resource economics':'Economics & Business',
        #'Aeronautics':'null',
        #'Cartography':'null',
        'Structural engineering':'Engineering',
        'Social psychology':'Psychiatry/Psychology',
        'Forestry':'Environment/Ecology',
        'Psychotherapist':'Psychiatry/Psychology',
        'Clinical psychology':'Psychiatry/Psychology',
        'Photochemistry':'Chemistry',
        #'Epistemology':'null',
        'Chemical physics':'Physics',
        'Zoology':'Plant & Animal Science',
        #'Biotechnology':'null',
        'Industrial organization':'Economics & Business',
        'Forensic engineering':'Engineering',
        'Economic geography':'Economics & Business',
        'Polymer science':'Materials Science',
        'Embedded system':'Computer Science',
        #'Cognitive science':'null',
        #'Nuclear medicine':'null',
        'Toxicology':'Pharmacology & Toxicology',
        'Criminology':'Social Sciences, general',
        #'Biological engineering':'null',
        #'Intensive Care Medicine':'null',
        'Computer security':'Computer Science',
        'Bioinformatics':'Computer Science',
        'Statistical physics':'Physics',
        'Welfare economics':'Economics & Business',
        'Economic system':'Economics & Business',
        'Environmental Engineering':'Engineering',
        #'Oncology':'null',
        'Organic chemistry':'Chemistry',
        'Law':'Social Sciences, general',
        #'Food science':'null',
        'Public Relations':'Economics & Business',
        #'Optoelectronics':'null',
        'Labour economics':'Economics & Business',
        'Civil Engineering':'Engineering',
        'Regional science':'Social Sciences, general',
        'Neuroscience':'Neuroscience & Behavior',
        'Horticulture':'Agricultural Sciences',
        'Natural language processing':'Computer Science',
        #'Fishery':'null',
        'Linguistics':'Social Sciences, general',
        'Theoretical computer science':'Computer Science',
        #'Medical emergency':'null',
        'Financial system':'Economics & Business',
        'Combinatorics':'Mathematics',
        'Classical economics':'Economics & Business',
        'Pattern recognition':'Computer Science',
        #'Orthodontics':'null',
        #'Anesthesia':'null',
        'Discrete mathematics':'Mathematics',
        'Environmental economics':'Economics & Business',
        'Atomic physics':'Physics',
        'Process management':'Economics & Business',
        'Engineering drawing':'Engineering',
        #'Computational biology':'null',
        'Microbiology':'Microbiology',
        'Mathematical optimization':'Mathematics',
        #'Paleontology':'null',
        'Meteorology':'Geosciences',
        'Biophysics':'Biology & Biochemistry',
        #'Humanities':'null',
        'Cognitive psychology':'Psychiatry/Psychology',
        'Immunology':'Immunology',
        'Water resource management':'Environment/Ecology',
        #'Knowledge management':'null',
        'Financial economics':'Economics & Business',
        #'Visual arts':'null',
        #'Nursing':'null',
        'Microeconomics':'Economics & Business',
        'Nuclear physics':'Physics',
        'Atmospheric sciences':'Geosciences',
        'Gender studies':'Social Sciences, general',
        'Geomorphology':'Geosciences',
        'Optics':'Physics',
        'Control engineering':'Engineering',
        #'Family medicine':'null',
        'Computer hardware':'Computer Science',
        #'Optometry':'null',
        'Machine learning':'Computer Science',
        #'Obstetrics':'null',
        'Mathematics education':'Social Sciences, general',
        'Polymer chemistry':'Chemistry',
        'Waste management':'Environment/Ecology',
        #'Computational science':'null',
        'Electronic engineering':'Engineering',
        'Physiology':'Biology & Biochemistry',
        'Economic growth':'Economics & Business',
        #'Control theory':'null',
        'Molecular physics':'Physics',
        #'Simulation':'null',
        'Thermodynamics':'Physics',
        'Pedagogy':'Social Sciences, general',
        'Anatomy':'Biology & Biochemistry',
        'Analytical chemistry':'Chemistry',
        'Soil science':'Geosciences',
        #'Risk analysis':'null',
        #'Literature':'null',
        'Aerospace Engineering':'Engineering',
        'Geotechnical engineering':'Engineering',
        'Mineralogy':'Geosciences',
        'Quantum electrodynamics':'Physics',
        'Petroleum Engineering':'Engineering',
        'Medical education':'Social Sciences, general',
        'Geophysics':'Geosciences',
        #'Process engineering':'null',
        'Botany':'Plant & Animal Science',
        'Petrology':'Geosciences',
        'Mechanical Engineering':'Engineering',
        'Speech recognition':'Computer Science',
        'Real-time computing':'Computer Science',
        'Public administration':'Social Sciences, general',
        'Socioeconomics':'Social Sciences, general',
        'Communication':'Social Sciences, general',
        'Programming language':'Computer Science',
        'Environmental protection':'Environment/Ecology',
        #'Management science':'null',
        #'Gynecology':'null',
        'Oceanography':'Geosciences',
        'Psychiatry':'Psychiatry/Psychology',
        'Medicinal chemistry':'Chemistry',
        #'Cardiology':'null',
        'Systems engineering':'Engineering',
        'Veterinary medicine':'Plant & Animal Science',
        'Advertising':'null',
        'Macroeconomics':'Economics & Business',
        'Theoretical physics':'Physics',
        #'Engineering physics':'null',
        #'Classics':'null',
        #'Medical physics':'null',
        'Market economy':'Economics & Business',
        #'Art history':'null',
        'Classical mechanics':'Physics',
        'Environmental health':'Environment/Ecology',
        'Public economics':'Economics & Business',
        'Pure mathematics':'Mathematics',
        'Cell biology':'Molecular Biology & Genetics',
        'Data mining':'Computer Science',
        'Computational chemistry':'Chemistry',
        #'Acoustics':'null',
        'Computational physics':'Physics',
        'Genealogy':'Social Sciences, general',
        'Computer Engineering':'Computer Science',
        'Algebra':'Mathematics',
        'Neoclassical economics':'Economics & Business',
        'International trade':'Economics & Business',
        'Business Administration':'Economics & Business',
        'Evolutionary biology':'Biology & Biochemistry',
        'Political Economy':'Economics & Business',
        'Psychoanalysis':'Psychiatry/Psychology',
        'Ecology':'Environment/Ecology',
        'Computer vision':'Computer Science',
        'Environmental resource management':'Environment/Ecology',
        'Animal science':'Plant & Animal Science',
        'Condensed matter physics':'Physics',
        'Media studies':'Social Sciences, general',
        'Commerce':'Economics & Business',
        'Database':'Computer Science',
        'Computer architecture':'Computer Science',
        'Library science':'Social Sciences, general',
        'Economic history':'Economics & Business',
        'Mining engineering':'Engineering',
        'Chemical Engineering':'Engineering',
        #'Radiology':'null',
        #'Virology':'null',
        'Keynesian economics':'Economics & Business',
        'General surgery':'Clinical Medicine',
        'Internal medicine':'null',
        'Economy':'Economics & Business',
        'Positive economics':'Economics & Business',
        'World Wide Web':'Computer Science',
        'Architectural engineering':'Engineering',
        'Biological system':'Biology & Biochemistry',
        'Operations management':'Economics & Business',
        'Genetics':'Molecular Biology & Genetics',
        #'Gastroenterology':'null'
    }