# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_auto_20160310_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvester',
            name='oai_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='harvester',
            name='oai_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
