# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160209_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='short_name',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
