# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20160308_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationurl',
            name='extraction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
