# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_publicationreference_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudyHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_level', models.SmallIntegerField()),
                ('parent_level', models.SmallIntegerField()),
                ('confidence', models.FloatField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldofstudyhierarchy_child', to='core.FieldOfStudy')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fieldofstudyhierarchy_parent', to='core.FieldOfStudy')),
            ],
        ),
    ]
