# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fieldofstudyhierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationFieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldofstudy_name', models.CharField(max_length=100)),
                ('level', models.SmallIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publication')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='publicationfieldofstudy',
            unique_together=set([('publication', 'fieldofstudy_name')]),
        ),
    ]
