# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160318_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authornamevariation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Author'),
        ),
    ]
