# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160319_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfieldofstudy',
            name='fieldofstudy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FieldOfStudy'),
        ),
    ]
