# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_publicationfieldofstudy_fieldofstudy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicationfieldofstudy',
            unique_together=set([('publication', 'fieldofstudy')]),
        ),
    ]
