# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20160327_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordFieldofstudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fieldofstudy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FieldOfStudy')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='keywordfieldofstudy',
            unique_together=set([('name', 'fieldofstudy')]),
        ),
    ]
