# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160327_1601'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='publicationauthoraffilation',
            unique_together=set([('publication', 'author')]),
        ),
    ]
