# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20160420_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authornameblock',
            name='name',
            field=models.CharField(db_index=True, max_length=52, unique=True),
        ),
    ]
