# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[(b'oai', b'oai'), (b'other', b'other')], max_length=50)),
                ('oai_url', models.URLField()),
                ('oai_identifier', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='OaiPmhProvider',
        ),
    ]
