run:
	python manage.py runserver
	
clear:
	python manage.py flush

tests:
	python manage.py test

test_main:
	python manage.py test core.tests
	
test_lib:
	python tests.py
	
run_citeseerx:
	python lib/CiteSeerExtractor/src/service.py 8081